k_list: [1, 3, 5, 10]
regression_tolerance: 0.05
baseline_metrics:
  avg_recall@5: 0.65
  avg_precision@5: 0.55
  avg_ndcg@10: 0.70
  avg_groundedness: 0.75
  avg_faithfulness: 0.78
  avg_abstention_unanswerable: 0.90
targets:
  recall@5: 0.70
  precision@5: 0.60
  ndcg@10: 0.75
  groundedness: 0.80
  faithfulness: 0.80
  abstention_unanswerable: 0.95
