k_list: [1, 3, 5, 10]
regression_tolerance: 0.05
baseline_metrics:
  avg_precision@5: 0.7
  avg_recall@5: 0.6
  avg_ndcg@10: 0.8
  avg_groundedness: 0.8
  avg_faithfulness: 0.75
  avg_answer_relevancy: 0.7
  avg_context_relevancy: 0.65
  avg_completeness: 0.8
