embed_model: "all-MiniLM-L6-v2"
rerank_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
collection_name: "healthcare_corpus"
top_n: 50
fusion_weight_dense: 0.7
fusion_weight_sparse: 0.3
k_list: [1, 3, 5, 10]
