name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Qdrant
      run: |
        docker run -d --name qdrant -p 6333:6333 qdrant/qdrant
        sleep 10

    - name: Ingest data
      run: python src/ingestion.py

    - name: Run evaluation
      run: |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        python -m src.evaluation --dataset data/golden/healthcare.jsonl --output docs/reports/$TIMESTAMP --config_id release
        cp -r docs/reports/$TIMESTAMP/* docs/reports/latest/

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/agentic-rag-assistant:${{ github.event.release.tag_name }}

    - name: Attach artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          docs/reports/latest/retrieval_metrics.csv
          docs/reports/latest/generation_metrics.csv
          docs/reports/latest/summary.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
